version: '3.8'
services:
  db:
    image: postgres:15.2-alpine
    container_name: banners_pg
    restart: always
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banners_dev
